In [1]:
#Q1. Create an array having consecutive natural numbers of size 6x3 and print it.

import numpy as np
array1=np.arange(18).reshape(6,3)
print("array1:{}".format(array1))

array1:[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [2]:
#Q2: Rename alll the coumns in the dataset as per your wish and save it in another dataframe and name it df2

import pandas as pd
df=pd.read_excel(r"C:\Users\abdussamad p\Desktop\Week 1 Dataset.xlsx")
df2=df.rename(columns={"Name":"peoples_names", "Income per month":"IPM", "State":"State_Name", "Age":"Peoples_Age", "Sex":"Male_or_Female", "Number of siblings":"NOS"})
print(df2)

  peoples_names  IPM     State_Name  Peoples_Age Male_or_Female  NOS
0             A   50     Tamil Nadu           23              M    0
1             B   34      Karnataka           37              F    3
2             C   54     Tamil Nadu           35              F    1
3             D   24  Uttar Pradesh           26              F    4
4             E   19          Bihar           59              M    5
5             F   21          Bihar           48              M    6
6             G   40          Delhi           30              F    2
7             H   20  Uttar Pradesh           72              M   10
8             I   30      Telangana           22              F    0
9             J   18    Chattisgarh           42              M    7


In [3]:
#q3 After you have created df2, make the same changes in the original dataframe using the inplace.

import pandas as pd
df2=pd.read_excel(r"C:\Users\abdussamad p\Desktop\Week 1 Dataset.xlsx")
df2.rename(columns={"Name":"peoples_names", "Income per month":"IPM", "State":"State_Name", "Age":"Peoples_Age", "Sex":"Male_or_Female", "Number of siblings":"NOS"},inplace=True)
print(df2)

  peoples_names  IPM     State_Name  Peoples_Age Male_or_Female  NOS
0             A   50     Tamil Nadu           23              M    0
1             B   34      Karnataka           37              F    3
2             C   54     Tamil Nadu           35              F    1
3             D   24  Uttar Pradesh           26              F    4
4             E   19          Bihar           59              M    5
5             F   21          Bihar           48              M    6
6             G   40          Delhi           30              F    2
7             H   20  Uttar Pradesh           72              M   10
8             I   30      Telangana           22              F    0
9             J   18    Chattisgarh           42              M    7


In [4]:
#Q4: Show only the columns information, sex and number of siblings.

import pandas as pd
df=pd.read_excel(r"C:\Users\abdussamad p\Desktop\Week 1 Dataset.xlsx")
print(df[["Sex", "Number of siblings"]])

  Sex  Number of siblings
0   M                   0
1   F                   3
2   F                   1
3   F                   4
4   M                   5
5   M                   6
6   F                   2
7   M                  10
8   F                   0
9   M                   7


In [11]:
#Q5: Use iloc method to print data from column 1 to 4 and rows 3 to 9

import pandas as pd
df=pd.read_excel(r"C:\Users\abdussamad p\Desktop\Week 1 Dataset.xlsx")
print(df.iloc[3:10,0:4])

  Name  Income per month          State  Age
3    D                24  Uttar Pradesh   26
4    E                19          Bihar   59
5    F                21          Bihar   48
6    G                40          Delhi   30
7    H                20  Uttar Pradesh   72
8    I                30      Telangana   22
9    J                18    Chattisgarh   42


In [6]:
#Q6: Find the total value count of number of siblings in the given dataset

import pandas as pd
df=pd.read_excel(r"C:\Users\abdussamad p\Desktop\Week 1 Dataset.xlsx")
print(df["Number of siblings"].value_counts())

0     2
10    1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: Number of siblings, dtype: int64


In [7]:
#independent variables

       #  age,no.of siblings

#dependent variables

       #-income per month

In [8]:
#Findings from the heat map:

#income per month decreases as age, and no. siblings increases.